---
deployment:
  tasks:
    - export BACKEND_PATH=/home/genmotor/chemical.garda-energi.com/
    - export FRONTEND_PATH=/home/genmotor/chemical.garda-energi.com/public/
    - /bin/rsync -avr --exclude '.git/' --exclude 'public/' . $BACKEND_PATH
    - /bin/rsync -avr public/ $FRONTEND_PATH
