---
deployment:
  tasks:
    - export BACKEND_PATH=/home/genmotor/chemical.garda-energi.com
    - /bin/rsync -vr --exclude '.git/' --exclude 'public/' . $BACKEND_PATH
    - /bin/rsync -vr ./public/* $BACKEND_PATH/public
